### ISSUE TITLE
No Issue

### ISSUE THREAD

**Issue by TylerHallTech** [GamerVerse722/Updated-GoGuardian-Bypass#2]
Glad to see someone updated the bypass I posted here: https://github.com/tyhallcsu/noguardian

Good work :P

**Comment by GamerVerse722** [comment]
Thanks, but your method is to accurately to disable the extention by going https://chrome.google.com/webstore_

My method is for the bookmark version remove the entire html for the website while getting the title to disguises it self from the tab viewer
